# Enter your per-environment constants below

development: &default
  constant1:  "value1"
  constant2:  "value2"
  facebook_app_id:      '244515575666539'
  facebook_secret_key:  '2ce9532a07461bf35f2ea18b50ff2afa'
  server_base:          'http://localhost:3000'
  mmt_key:              '5CAD254CF141A'
  admin_uid:            '571409218,1452186072'

production:

  constant1:  "value1"
  constant2:  "value2"
  facebook_app_id:      '367153893359066'
  facebook_secret_key:  'a682990551f7dc4b11dde5a7ffe375b6'
  server_base:          'http://whispering-plains-8323.herokuapp.com'
  mmt_key:              '5CAD254CF141A'
  admin_uid:            '571409218,1452186072'
  <<: *default
  constant1:  "overriden value1"


  
test:
  <<: *default